version: '3'
services:
  # load balancing
  eureka:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports: # only for debugging purposes will be 8761 without host-port forwarding in prod
      - "8761:8761"
  ###

  # session handling
  redis:
      image: "redis:latest"
  ###

  rabbitmq:
    image: rabbitmq

  # zuul-gateway
  zuul:
    build:
      context: ./zuul-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
      - redis
      - zuul-db

  zuul-db:
    image: "postgres:10"
    ports:
     - "5435"
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz

  user:
    build:
      context: ./user/
      dockerfile: Dockerfile
    ports:
      - "8082"
    depends_on:
      - redis
      - user-db
      - zuul

  # User-service db
  user-db:
    image: "postgres:10"
    ports:
       - "5434"
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz
  ###

  # quiz-service, creates two instances, to be able to handle more traffic and make it more robust.
  # Will be load-balanced with eureka
  quiz1:
    build:
      context: ./quiz/
      dockerfile: Dockerfile
    ports:
      - "8083"
    depends_on:
      - quiz-db
      - zuul

  quiz-db:
    image: "postgres:10"
    ports:
      - "5433"
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz

  # highscore service
  highscore:
    build:
      context: ./highscore/
      dockerfile: Dockerfile
    ports:
      - "8085"
    depends_on:
      - rabbitmq
      - highscore-db
      - zuul
    environment:
      - "SPRING_PROFILES_ACTIVE=dc"


  highscore2:
    build:
      context: ./highscore/
      dockerfile: Dockerfile
    ports:
      - "8086"
    depends_on:
      - rabbitmq
      - highscore-db
      - zuul
    environment:
      - "SPRING_PROFILES_ACTIVE=dc"

  highscore-db:
      image: "postgres:10"
      ports:
        - "5435"
      environment:
        POSTGRES_DB: quiz
        POSTGRES_USER: quiz