server:
  port: "8083"
  context-path: "/apiV1"
spring:
  application:
    name: "quiz-service"
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  sessions: NEVER