version: '3'
services:
  rabbitmq:
    image: rabbitmq:3

  highscore:
      build:
        context: ../highscore
        dockerfile: Dockerfile
      ports:
        - "8085:8085"

  quiz:
    build:
      context: ../quiz
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=development"