zuul:
  routes:
    quiz-service:
      path: "/quiz/**"
    user-service:
      path: "/user/**"

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: "zuul"


