zuul:
  routes:
    quiz-service:
      path: "/quiz/**"
      sensitive-headers:
    user-service:
      path: "/user/details/**"
      sensitive-headers:
    highscore-service:
      path: "/highscore/**"
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: "zuul"
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://zuul-db:5432/quiz"
    username: "quiz"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update


security:
  session: ALWAYS

logging:
  level:
    org.springframework.security: debug



